### ISSUE TITLE
Curious about the runway to first release

### ISSUE THREAD

**Issue by wuhland** [geops/react-spatial#290]
Very useful library! It looks like you have a lot here and I'm curious about the runway to first release. Are there major features that you are looki.mapng to add before graduating from Beta or are there stability issues that need addressing?

**Comment by oterral** [comment]
Thanks for your interest  @wuhland !!  We are always in beta because some code is suggest  to change any time.  We use the library in all our project so the spatial components are pretty stable for a while now . The future of all others components (Menu,Form, Basic sections in the doc) and we want to handle styling  are not clear. But we are going to clarify this before the end of the year.
